Arreglo[12] de Entero numeros
Entero i, suma

Inicio
    Escriba "Prueba Lea"
    Llamar nueva_linea()
    suma <- 0
    Para i <- 1 Hasta 12 Haga
		Escriba "Nota ", i,':'
        Lea numeros[i]
	Fin Para

    Para i <- 1 Hasta 12 Haga
		suma <- suma + numeros[i]
	Fin Para

    Si suma / 12 >= 60 entonces
        Escriba "Paso la clase, promedio:", suma/12
    sino
        Escriba "No paso la clase, promedio:", suma/12
    fin si
Final